---
- name: Install Docker and run container
  hosts: 18.209.16.175
  become: yes
  tasks:
    - name: Update the apt package index
      apt:
        update_cache: yes

    - name: Add Docker’s official GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Set up the stable repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable
        state: present

    - name: Install Docker CE
      apt:
        name: docker-ce
        state: present

    - name: Ensure Docker is running
      service:
        name: docker
        state: started
        enabled: yes

    - name: Install Git
      apt:
        name: git
        state: present

    - name: Clone the GitHub repository
      git:
        repo: 'https://github.com/phlaureedee/finalprojectrepo.git'
        dest: /tmp/finalprojectrepo
        version: master

    - name: Build Docker image
      command: docker build -t mywebapp:v1 /tmp/finalprojectrepo

    - name: Run Docker container
      command: docker run -d --name myapp -p 30000:8080 mywebapp:v1
...
          
