---
- name: Build Docker image and run container
  hosts: all
  become: yes
  tasks:
    - name: Ensure Git is installed
      apt:
        name: git
        state: present

    - name: Clone the GitHub repository
      git:
        repo: 'https://github.com/jawadsaeed26/myproject.git'
        dest: /tmp/java-app
        version: main

    - name: Build Docker image
      command: docker build -t mywebapp:v1 /tmp/java-app

    - name: Run Docker container
      command: docker run -d --name myapp -p 3000:8080 mywebapp:v1
...